[package]
name = "rustle"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.76"
js-sys = "0.3.58"

[lib]
crate-type = ["cdylib"]

[profile.dev]
codegen-units = 1

[profile.release]
codegen-units = 1